### ISSUE TITLE
Extraneous Statement

### ISSUE THREAD

**Issue by tom131313** [anfractuosity/LSD#1]
Thanks for this conversion to Java.  GUI.java line 67 was part of the original example in "C" to print the 7 values associated with a line but in this conversion it only wastes a little time trying to stuff the same line into the hashSet seven times.  Four of the values for "j" are hard-coded and the other three values are ignored; the loop is no longer used as intended.

```java
for (int j = 0; j < 7; j++)
```

**Comment by anfractuosity** [comment]
Good spot! Thanks for reporting this, will get it fixed soon.

**Comment by anfractuosity** [comment]
Just fixed, thanks.
